// Generated by generate_state_machine_cpp.py from state_machine.puml
// DO NOT EDIT MANUALLY.

#include "state_machine_generated.h"

namespace app {

void StateMachine::dispatch(Event event, Context& ctx) {
    switch (state_) {
    case State::Boot:
        if (event == Event::EV_BOOT_DONE && guard_init_ok(ctx)) {
            app_init_success();
            state_ = State::Start;
        } else if (event == Event::EV_ERROR && guard_ble_init_failed(ctx)) {
            app_on_error_ble();
            state_ = State::Error;
        } else if (event == Event::EV_ERROR && guard_hw_init_failed(ctx)) {
            app_on_error_hw();
            state_ = State::Halted;
        }
        break;
    case State::Connecting:
        if (event == Event::EV_CONNECTED) {
            on_peer_connected();
            state_ = State::Gameplay;
        } else if (event == Event::EV_DISCONNECTED) {
            on_peer_disconnected();
            state_ = State::Disconnected;
        } else if (event == Event::EV_ERROR) {
            app_on_error();
            state_ = State::Error;
        }
        break;
    case State::Disconnected:
        if (event == Event::EV_RETRY) {
            reset_and_return_start();
            state_ = State::Start;
        } else if (event == Event::EV_ERROR) {
            app_on_error();
            state_ = State::Error;
        }
        break;
    case State::Error:
        if (event == Event::EV_RETRY) {
            reset_and_return_start();
            state_ = State::Start;
        } else if (event == Event::EV_ERROR && guard_fatal(ctx)) {
            app_on_error_fatal();
            state_ = State::Halted;
        }
        break;
    case State::Evaluating:
        if (event == Event::EV_EVALUATE) {
            evaluate_and_show_result();
            state_ = State::Result;
        } else if (event == Event::EV_ERROR) {
            app_on_error();
            state_ = State::Error;
        }
        break;
    case State::Gameplay:
        if (event == Event::EV_MOVE_ROCK && guard_peer_move_received(ctx)) {
            on_local_move_rock_complete();
            state_ = State::Evaluating;
        } else if (event == Event::EV_MOVE_PAPER && guard_peer_move_received(ctx)) {
            on_local_move_paper_complete();
            state_ = State::Evaluating;
        } else if (event == Event::EV_MOVE_SCISSORS && guard_peer_move_received(ctx)) {
            on_local_move_scissors_complete();
            state_ = State::Evaluating;
        } else if (event == Event::EV_MOVE_ROCK && guard_not_peer_move_received(ctx)) {
            on_local_move_rock_pending();
            state_ = State::Gameplay;
        } else if (event == Event::EV_MOVE_PAPER && guard_not_peer_move_received(ctx)) {
            on_local_move_paper_pending();
            state_ = State::Gameplay;
        } else if (event == Event::EV_MOVE_SCISSORS && guard_not_peer_move_received(ctx)) {
            on_local_move_scissors_pending();
            state_ = State::Gameplay;
        } else if (event == Event::EV_PEER_MOVE_RECEIVED && guard_local_move_chosen(ctx)) {
            on_peer_move_complete();
            state_ = State::Evaluating;
        } else if (event == Event::EV_PEER_MOVE_RECEIVED && guard_not_local_move_chosen(ctx)) {
            on_peer_move_pending();
            state_ = State::Gameplay;
        } else if (event == Event::EV_DISCONNECTED) {
            on_peer_disconnected();
            state_ = State::Disconnected;
        } else if (event == Event::EV_ERROR) {
            app_on_error();
            state_ = State::Error;
        }
        break;
    case State::Halted:
        break;
    case State::PeerSearch:
        if (event == Event::EV_PEER_FOUND) {
            on_peer_found();
            state_ = State::RoleNegotiating;
        } else if (event == Event::EV_PEER_TIMEOUT) {
            on_discovery_timeout();
            state_ = State::SinglePlayerFallback;
        } else if (event == Event::EV_CANCEL) {
            on_cancel_button();
            state_ = State::Start;
        } else if (event == Event::EV_ERROR) {
            app_on_error();
            state_ = State::Error;
        }
        break;
    case State::Result:
        if (event == Event::EV_PLAY_AGAIN && guard_game_mode_eq_MODE_MULTI_PLAYER(ctx)) {
            start_new_round();
            state_ = State::Gameplay;
        } else if (event == Event::EV_PLAY_AGAIN && guard_game_mode_eq_MODE_SINGLE_PLAYER(ctx)) {
            start_new_round();
            state_ = State::SinglePlayerFallback;
        } else if (event == Event::EV_DISCONNECTED) {
            on_peer_disconnected();
            state_ = State::Disconnected;
        } else if (event == Event::EV_ERROR) {
            app_on_error();
            state_ = State::Error;
        }
        break;
    case State::RoleNegotiating:
        if (event == Event::EV_ROLE_RESOLVED && guard_role_host(ctx)) {
            start_advertising_host();
            state_ = State::Connecting;
        } else if (event == Event::EV_ROLE_RESOLVED && guard_role_join(ctx)) {
            start_scanning_join();
            state_ = State::Connecting;
        } else if (event == Event::EV_ERROR) {
            app_on_error();
            state_ = State::Error;
        }
        break;
    case State::SinglePlayerFallback:
        if (event == Event::EV_MOVE_ROCK) {
            on_singleplayer_move_rock();
            state_ = State::Evaluating;
        } else if (event == Event::EV_MOVE_PAPER) {
            on_singleplayer_move_paper();
            state_ = State::Evaluating;
        } else if (event == Event::EV_MOVE_SCISSORS) {
            on_singleplayer_move_scissors();
            state_ = State::Evaluating;
        } else if (event == Event::EV_ERROR) {
            app_on_error();
            state_ = State::Error;
        }
        break;
    case State::Start:
        if (event == Event::EV_PLAY) {
            on_play_button();
            state_ = State::PeerSearch;
        } else if (event == Event::EV_ERROR) {
            app_on_error();
            state_ = State::Error;
        }
        break;
    default:
        break;
    }
}

} // namespace app
